// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL9P_Y9uJQz2dRRA1y9k_Xq_NkX5gC00M',
    appId: '1:937400404540:web:64f1b50ce20ddb152a9139',
    messagingSenderId: '937400404540',
    projectId: 'solar-cool',
    authDomain: 'solar-cool.firebaseapp.com',
    databaseURL: 'https://solar-cool-default-rtdb.firebaseio.com',
    storageBucket: 'solar-cool.firebasestorage.app',
    measurementId: 'G-MCZZ6L7ZJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD6l_NMdRAgHGGDMK8FhY-9MzY0nGIgSg',
    appId: '1:937400404540:android:e3f4032f6dea72a62a9139',
    messagingSenderId: '937400404540',
    projectId: 'solar-cool',
    databaseURL: 'https://solar-cool-default-rtdb.firebaseio.com',
    storageBucket: 'solar-cool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7s6hv64knLfzcHFQ1w3UOqELew1z7A48',
    appId: '1:937400404540:ios:c2308323450d08fe2a9139',
    messagingSenderId: '937400404540',
    projectId: 'solar-cool',
    databaseURL: 'https://solar-cool-default-rtdb.firebaseio.com',
    storageBucket: 'solar-cool.firebasestorage.app',
    iosBundleId: 'com.example.solarCool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7s6hv64knLfzcHFQ1w3UOqELew1z7A48',
    appId: '1:937400404540:ios:c2308323450d08fe2a9139',
    messagingSenderId: '937400404540',
    projectId: 'solar-cool',
    databaseURL: 'https://solar-cool-default-rtdb.firebaseio.com',
    storageBucket: 'solar-cool.firebasestorage.app',
    iosBundleId: 'com.example.solarCool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL9P_Y9uJQz2dRRA1y9k_Xq_NkX5gC00M',
    appId: '1:937400404540:web:dfe6d85514da59b52a9139',
    messagingSenderId: '937400404540',
    projectId: 'solar-cool',
    authDomain: 'solar-cool.firebaseapp.com',
    databaseURL: 'https://solar-cool-default-rtdb.firebaseio.com',
    storageBucket: 'solar-cool.firebasestorage.app',
    measurementId: 'G-TB72QVYXC1',
  );
}
